In [1]:
import numpy as np
import gym

In [2]:
#loading the enviroment 
env = gym.make('FrozenLake-v0')

In [3]:
#Learning theQ-table non-neural network way
Q = np.zeros([env.observation_space.n, env.action_space.n])
#setting all the initial values of the table to zero
lr = 0.8 #learning rate
y = 0.95
num_episodes = 2000

r_list = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    while j < 99:
        j += 1
        a = np.argmax(Q[s,:] + np.random.randn(1, env.action_space.n)*(1./(i+1)))
        s1,r,d,_ = env.step(a)
        Q[s,a] = Q[s,a] + lr*(r+y*np.max(Q[s1,:])-Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    r_list.append(rAll)

In [5]:
print ("Score over time:" + str(sum(r_list)/num_episodes))

Score over time:0.4695


In [7]:
print (Q)

[[1.74468030e-01 5.72451393e-03 3.73086906e-03 7.21076981e-03]
 [1.03355697e-03 5.98546810e-04 6.31348825e-04 2.15968947e-01]
 [1.63476693e-03 1.22915091e-03 1.43925545e-03 2.28487192e-01]
 [4.68514499e-04 8.81691616e-04 6.89022179e-04 7.48426689e-02]
 [3.80986643e-01 1.26701831e-03 2.02390463e-04 2.16032219e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.45346069e-01 6.72565515e-04 2.03955330e-06 3.24650360e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.95473822e-04 1.41047199e-03 0.00000000e+00 4.79110835e-01]
 [1.80224111e-03 2.55044394e-01 1.41756649e-03 5.89708234e-04]
 [7.47435663e-01 3.77374668e-05 4.14991338e-05 6.93896688e-05]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.00828391e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.82936701e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000

In [8]:
r_list

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0